# _config.yaml
title: "Jose Garza"
author: "https://github.com/joselgarza"
copyright: "Â© 2025 Jose Garza"
theme: minima

# Top navigation links
header_pages:
- index.md
- code-review.md
- enhancement-one.md
- enhancement-two.md
- enhancement-three.md
